/**
 * /limitations — what Avena does not know, published daily by the system
 * itself. Architectural Commitment 10.
 */

import type { Metadata } from 'next';
import Link from 'next/link';
import { Nav } from '@/components/v2/Nav';
import { Footer } from '@/components/v2/Footer';
import { activeLimitations } from '@/lib/limitations';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Limitations · what Avena does not know',
  description: 'Avena Terminal publishes its own limitations daily — coverage gaps, low-confidence zones, failed ingestions, stale feeds. Generated by the system itself from real telemetry, not curated.',
  alternates: { canonical: 'https://avenaterminal.com/limitations' },
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'TechArticle',
  headline: 'Avena Terminal — System Limitations',
  description: 'Self-generated daily disclosure of coverage gaps, low-confidence zones, ingestion failures, and stale feeds.',
  url: 'https://avenaterminal.com/limitations',
  publisher: { '@type': 'Organization', name: 'Avena Terminal' },
};

const SEVERITY_ORDER: Record<string, number> = { significant: 0, moderate: 1, minor: 2 };
const SEVERITY_COLOR: Record<string, string> = {
  significant: 'hsl(var(--av-destructive))',
  moderate:    'hsl(var(--av-warning))',
  minor:       'hsl(var(--av-muted-foreground))',
};

const CATEGORY_LABEL: Record<string, string> = {
  coverage:    'Coverage gap',
  confidence:  'Low confidence',
  ingestion:   'Ingestion failure',
  methodology: 'Methodology gap',
  staleness:   'Data staleness',
};

export default async function LimitationsPage() {
  const rows = await activeLimitations();
  rows.sort((a, b) => (SEVERITY_ORDER[a.severity] ?? 9) - (SEVERITY_ORDER[b.severity] ?? 9));

  const byCategory = new Map<string, typeof rows>();
  for (const r of rows) {
    const list = byCategory.get(r.limitation_category) ?? [];
    list.push(r);
    byCategory.set(r.limitation_category, list);
  }

  const counts = {
    significant: rows.filter(r => r.severity === 'significant').length,
    moderate:    rows.filter(r => r.severity === 'moderate').length,
    minor:       rows.filter(r => r.severity === 'minor').length,
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <Nav />
      <main className="min-h-screen">
        {/* Hero */}
        <section className="mx-auto max-w-[1400px] px-5 sm:px-12 pt-16 pb-10">
          <div className="font-mono text-[10px] uppercase tracking-[0.32em] text-gold mb-3">
            Architectural Commitment 10 · Self-Aware Limitations
          </div>
          <h1 className="font-serif text-5xl md:text-6xl font-light text-foreground mb-4 leading-[1.05]">
            What Avena does not know.
          </h1>
          <p className="max-w-3xl text-base text-muted-foreground leading-relaxed">
            Most data vendors hide weakness. The IMF, ECB Financial Stability Review, and FT publish theirs. We do the same — daily, automatically, generated by the system from real telemetry. Coverage gaps, low-confidence zones, ingestion failures, and stale feeds are all flagged here before a customer has to find them.
          </p>
          <p className="mt-4 max-w-3xl text-sm text-muted-foreground/85 leading-relaxed">
            If this page looks dishonestly empty, the cron is broken. If it looks suspiciously full, we are being honest about a young dataset. Either reading is more useful than a marketing page.
          </p>
        </section>

        {/* Counts strip */}
        <section className="mx-auto max-w-[1400px] px-5 sm:px-12 pb-10">
          <div className="grid grid-cols-3 gap-4">
            {(['significant', 'moderate', 'minor'] as const).map(sev => (
              <div key={sev} className="rounded-sm border p-5" style={{ borderColor: 'hsl(var(--av-border) / 0.6)' }}>
                <div className="font-mono text-[10px] uppercase tracking-[0.32em]" style={{ color: SEVERITY_COLOR[sev] }}>
                  {sev}
                </div>
                <div className="mt-2 font-serif text-4xl font-light text-foreground tabular">{counts[sev]}</div>
                <div className="mt-1 font-mono text-[9px] uppercase tracking-[0.22em] text-muted-foreground">active findings</div>
              </div>
            ))}
          </div>
        </section>

        {/* Findings grouped by category */}
        <section className="mx-auto max-w-[1400px] px-5 sm:px-12 pb-16">
          {rows.length === 0 ? (
            <div className="rounded-sm border p-10" style={{ borderColor: 'hsl(var(--av-border) / 0.4)' }}>
              <div className="font-mono text-[10px] uppercase tracking-[0.32em] text-muted-foreground mb-2">No active findings</div>
              <p className="text-sm text-foreground/85">
                The compiler ran clean on its last pass. Either we genuinely have no flagged limitations (rare and worth being suspicious of) or the daily cron has not yet run for this environment. Check back tomorrow.
              </p>
            </div>
          ) : (
            <div className="space-y-12">
              {Array.from(byCategory.entries()).map(([cat, items]) => (
                <div key={cat}>
                  <div className="font-mono text-[10px] uppercase tracking-[0.32em] text-gold mb-3">
                    {CATEGORY_LABEL[cat] ?? cat} · {items.length}
                  </div>
                  <div className="space-y-3">
                    {items.map(r => (
                      <div key={r.id} className="rounded-sm border p-5" style={{ borderColor: 'hsl(var(--av-border) / 0.6)', background: 'hsl(var(--av-surface) / 0.3)' }}>
                        <div className="flex items-start justify-between gap-4 mb-2">
                          <div className="flex items-center gap-3">
                            <span className="font-mono text-[9px] uppercase tracking-[0.32em] px-2 py-1 rounded-sm" style={{ color: SEVERITY_COLOR[r.severity], background: 'hsl(var(--av-background))' }}>
                              {r.severity}
                            </span>
                            <span className="font-mono text-[10px] text-muted-foreground">
                              {r.affected_areas.join(' · ')}
                            </span>
                          </div>
                          <span className="font-mono text-[9px] uppercase tracking-[0.22em] text-muted-foreground/70 whitespace-nowrap">
                            {r.reported_at.slice(0, 10)}
                          </span>
                        </div>
                        <p className="text-sm text-foreground/90 leading-relaxed">{r.description}</p>
                        <div className="mt-3 flex flex-wrap items-center gap-4 font-mono text-[10px] text-muted-foreground">
                          <span><span className="text-foreground/70">{r.detected_metric}:</span> <span className="text-foreground tabular">{r.detected_value}</span> <span className="text-muted-foreground/60">(threshold {r.threshold_value})</span></span>
                          {r.remediation_status && (
                            <span><span className="text-foreground/70">status:</span> <span className="text-foreground">{r.remediation_status}</span></span>
                          )}
                        </div>
                        {r.remediation_note && (
                          <p className="mt-2 text-xs text-muted-foreground italic">{r.remediation_note}</p>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>

        {/* Footer note */}
        <section className="mx-auto max-w-[1400px] px-5 sm:px-12 pb-20">
          <div className="rounded-sm border p-6" style={{ borderColor: 'hsl(var(--av-border) / 0.4)', background: 'hsl(var(--av-surface) / 0.2)' }}>
            <div className="font-mono text-[10px] uppercase tracking-[0.32em] text-gold mb-2">How this page is generated</div>
            <p className="text-sm text-foreground/85 leading-relaxed max-w-3xl">
              A cron job at 02:30 UTC daily walks four passes: per-country coverage counts vs threshold; failed cron runs in the last 24h; AVM confidence rolling-averaged by town over 30 days; and macro feed staleness vs schedule. Findings that no longer trigger are automatically resolved. The full compiler source lives at <span className="font-mono text-foreground">src/lib/limitations.ts</span> and is reproducible from the event store.
            </p>
            <div className="mt-4 flex flex-wrap gap-3 font-mono text-[10px] uppercase tracking-[0.22em]">
              <Link href="/timetravel?type=limitation" className="text-foreground/85 hover:text-primary">Replay limitation history →</Link>
              <Link href="/defensibility#reproducibility" className="text-foreground/85 hover:text-primary">Reproducibility →</Link>
              <Link href="/governance" className="text-foreground/85 hover:text-primary">Governance →</Link>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
