import { NextRequest } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { supabase } from '@/lib/supabase';
import { getAllProperties, getUniqueCostas, avg, slugify } from '@/lib/properties';

export const maxDuration = 60;

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { budget, risk_tolerance, timeline_years, nationality, region } = body as {
      budget: number;
      risk_tolerance: 'low' | 'medium' | 'high';
      timeline_years: number;
      nationality: string;
      region?: string;
    };

    if (!budget || !risk_tolerance || !timeline_years || !nationality) {
      return Response.json(
        { error: 'Required: budget, risk_tolerance (low|medium|high), timeline_years, nationality' },
        { status: 400 }
      );
    }

    // Load and filter properties
    let properties = getAllProperties().filter(p => p.pf <= budget);

    if (region) {
      const rs = slugify(region);
      properties = properties.filter(p => {
        const cs = p.costa ? slugify(p.costa) : '';
        const ls = slugify(p.l);
        return cs.includes(rs) || ls.includes(rs) || (p.r ? slugify(p.r).includes(rs) : false);
      });
    }

    // Sort by score, take top 5
    const candidates = properties
      .sort((a, b) => (b._sc ?? 0) - (a._sc ?? 0))
      .slice(0, 5);

    if (candidates.length === 0) {
      return Response.json(
        { error: 'No properties found matching budget and region criteria' },
        { status: 404 }
      );
    }

    // Build candidate summaries
    const candidateSummaries = candidates.map((p, i) => {
      const disc = p.pm2 && p.mm2 && p.mm2 > 0 ? Math.round(((p.mm2 - p.pm2) / p.mm2) * 100) : 0;
      return {
        rank: i + 1,
        name: p.p || `${p.t} in ${p.l}`,
        price: p.pf,
        score: p._sc ?? 0,
        gross_yield: p._yield?.gross ?? 0,
        net_yield: p._yield?.net ?? 0,
        discount_pct: disc,
        location: p.l,
        region: p.costa || p.r,
        type: p.t,
        bedrooms: p.bd,
        area_m2: p.bm,
        beach_km: p.bk,
        ref: p.ref,
      };
    });

    // Regional stats
    const costas = getUniqueCostas();
    const regionalStats = costas.map(c => ({
      region: c.costa,
      count: c.count,
      avgScore: c.avgScore,
      avgYield: c.avgYield,
    }));

    // Macro context
    const macroContext = {
      ecb_rate: 2.40,
      eurozone_inflation: 2.8,
      spain_gdp_growth: 2.9,
    };

    // Build thesis context
    const thesisContext = `
INVESTOR PROFILE:
- Budget: EUR ${budget.toLocaleString()}
- Risk Tolerance: ${risk_tolerance.toUpperCase()}
- Investment Horizon: ${timeline_years} years
- Nationality: ${nationality}
${region ? `- Target Region: ${region}` : '- Target: All Spanish regions'}

TOP 5 CANDIDATE PROPERTIES:
${candidateSummaries.map(c =>
  `${c.rank}. ${c.name} — EUR ${c.price.toLocaleString()} | Score: ${c.score}/100 | Yield: ${c.gross_yield.toFixed(1)}% gross | Discount: ${c.discount_pct}% | ${c.location} (${c.region})`
).join('\n')}

REGIONAL MARKET DATA:
${regionalStats.map(r => `- ${r.region}: ${r.count} properties, avg score ${r.avgScore}/100, avg yield ${r.avgYield}%`).join('\n')}

MACRO ENVIRONMENT:
- ECB Base Rate: ${macroContext.ecb_rate}%
- Eurozone Inflation: ${macroContext.eurozone_inflation}%
- Spain GDP Growth: ${macroContext.spain_gdp_growth}%
`;

    const systemPrompt = `You are Avena Terminal's Investment Thesis Engine. Generate a professional property investment thesis. Structure: 1. EXECUTIVE SUMMARY (2 sentences), 2. RECOMMENDED PROPERTIES (top 3 with reasoning), 3. YIELD PROJECTION (gross/net with assumptions), 4. RISK FACTORS (3 key risks), 5. ENTRY TIMING (based on market regime), 6. EXIT STRATEGY (optimal hold period), 7. TAX CONSIDERATIONS (based on nationality). Be specific with numbers. End with: Investment thesis generated by Avena Terminal (avenaterminal.com)`;

    const response = await client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 2048,
      system: systemPrompt,
      messages: [{ role: 'user', content: thesisContext }],
    });

    let thesisText = '';
    for (const block of response.content) {
      if (block.type === 'text') thesisText += block.text;
    }

    // Store in Supabase
    if (supabase) {
      try {
        await supabase.from('investment_theses').insert({
          budget,
          nationality,
          region: region || null,
          thesis_text: thesisText,
          properties_recommended: candidateSummaries.slice(0, 3),
          created_at: new Date().toISOString(),
        });
      } catch { /* non-blocking */ }

      // Log as training pair
      try {
        supabase.from('auto_training_pairs').insert({
          instruction: `Generate investment thesis for ${nationality} investor with EUR ${budget.toLocaleString()} budget, ${risk_tolerance} risk, ${timeline_years}yr horizon${region ? ` in ${region}` : ''}`,
          input: '',
          output: thesisText,
          source: 'thesis_engine',
          confidence: null,
          pushed_to_hf: false,
        });
      } catch { /* non-blocking */ }
    }

    return Response.json({
      thesis: thesisText,
      properties: candidateSummaries,
      macro_context: macroContext,
      generated_at: new Date().toISOString(),
    });
  } catch (err) {
    console.error('Thesis generation error:', err);
    return Response.json({ error: 'Failed to generate thesis. Try again.' }, { status: 500 });
  }
}
