import { Metadata } from 'next';
import Link from 'next/link';
import { Nav } from '@/components/v2/Nav';
import { Footer } from '@/components/v2/Footer';

export const revalidate = 86400;

export const metadata: Metadata = {
  title: 'Changelog — What\'s New on Avena Terminal',
  description: 'Every shipped feature, every system, every agent. The chronological build log of Avena Terminal.',
  alternates: { canonical: 'https://avenaterminal.com/changelog' },
};

interface ChangelogEntry {
  date: string;
  title: string;
  tag: 'SHIPPED' | 'SYSTEM' | 'FEATURE' | 'AGENT' | 'API' | 'DESIGN';
  summary: string;
  links?: Array<{ label: string; href: string }>;
}

const CHANGELOG: ChangelogEntry[] = [
  {
    date: '2026-04-19',
    title: 'The Prediction Ledger',
    tag: 'SYSTEM',
    summary: 'Public property-AI accuracy benchmark. 10 daily predictions generated by Agent Nostradamus, verified by Agent Arbiter at the 365-day mark. Anyone can challenge Avena — accuracy scores public. 3 new Supabase tables, 4 API routes, full leaderboard.',
    links: [
      { label: 'The Ledger', href: '/predictions' },
      { label: 'Leaderboard', href: '/predictions/leaderboard' },
    ],
  },
  {
    date: '2026-04-19',
    title: 'Agent Prometheus — Question Ownership Engine',
    tag: 'AGENT',
    summary: '14th agent. Runs daily at 04:00 UTC. Harvests questions from /api/aeo/questions, user queue, and Agent Shadow\'s citation gaps. Drafts atomic-fact answers via Claude Sonnet. Publishes to Supabase generated_answers. IndexNow-pinged within minutes.',
    links: [
      { label: 'Swarm', href: '/swarm' },
      { label: 'Status API', href: '/api/prometheus/status' },
    ],
  },
  {
    date: '2026-04-19',
    title: 'Embargo Intelligence Protocol',
    tag: 'FEATURE',
    summary: 'Journalists get 24h early access to next-cycle APCI/APYI values. Form + per-outlet Bearer keys + audit log. Puts Avena in press articles before competitors see the data.',
    links: [
      { label: 'Press Embargo', href: '/press/embargo' },
    ],
  },
  {
    date: '2026-04-19',
    title: 'v2 Luxe Editorial Design — Full Migration',
    tag: 'DESIGN',
    summary: '75+ pages migrated from dark terminal to warm luxe editorial (serif headings, gold accents, mono data). Every click on Avena now matches the new design system. Shared Nav + Footer components. ProModal popup replaces full /pro page.',
    links: [
      { label: 'Homepage', href: '/' },
      { label: 'PRO', href: '/pro' },
    ],
  },
  {
    date: '2026-04-19',
    title: 'Live Citations Counter',
    tag: 'FEATURE',
    summary: 'Real-time MCP tool call counter on homepage. Polls /api/cited every 30 seconds. Animated "+N" delta when count ticks. Links to full /ai-citations dashboard.',
    links: [
      { label: 'Citations', href: '/ai-citations' },
    ],
  },
  {
    date: '2026-04-19',
    title: 'Agent Atlas — Citation Intelligence',
    tag: 'AGENT',
    summary: '13th agent. Daily 03:00 UTC. Queries Perplexity with 50 tracked property questions, finds gaps where Avena isn\'t cited but competitors are, generates citation-optimized content via Claude.',
    links: [
      { label: 'Swarm', href: '/swarm' },
    ],
  },
  {
    date: '2026-04-18',
    title: 'Operation CEO Attention — PropertyEval + Colosseum + Observatory',
    tag: 'SYSTEM',
    summary: '1,000-question PropertyEval benchmark with AI leaderboard. Public AI Colosseum daily battles. Observatory watching the dataset improve live. Universal Context Protocol for one-line LLM enrichment. Zero-knowledge range proofs.',
    links: [
      { label: 'Benchmark', href: '/benchmark' },
      { label: 'Colosseum', href: '/colosseum' },
      { label: 'Observatory', href: '/observatory' },
    ],
  },
  {
    date: '2026-04-18',
    title: 'Operation Permanent First',
    tag: 'SYSTEM',
    summary: 'Citation fortress. X-Cite-As headers on every API response. /cite citation generator for every Avena system (APA, BibTeX, Chicago, Harvard, MLA). Steganographic watermark verification. Copy detection cron. Trademark brief. Priority timeline with SHA-256 hashed inventions.',
    links: [
      { label: 'Cite', href: '/cite' },
      { label: 'Timeline', href: '/timeline' },
    ],
  },
  {
    date: '2026-04-17',
    title: 'Operation Map Domination — Index Family + Manifesto + Data Commons',
    tag: 'SYSTEM',
    summary: '5 live European property indices (APCI, APYI, APLI, APRI, APSI) in one family. Autonomy Declaration manifesto. SHA-256 data verification page. CC BY 4.0 open dataset endpoint. AI partnership profile. Atom feed for intelligence syndication.',
    links: [
      { label: 'Indices', href: '/indices' },
      { label: 'Manifesto', href: '/manifesto' },
      { label: 'Data Commons', href: '/data-commons' },
    ],
  },
  {
    date: '2026-04-16',
    title: 'Knowledge Graph Injection',
    tag: 'API',
    summary: 'Wikidata QuickStatements export. RDF/Turtle with avena: namespace. Read-only SPARQL endpoint. NUTS2/NUTS3 Eurostat integration. OSM overlay export. .well-known/ai-data-policy.json for AI crawlers. GitHub citation.cff.',
    links: [
      { label: 'SPARQL', href: '/api/v1/sparql' },
      { label: 'AI Policy', href: '/.well-known/ai-data-policy.json' },
    ],
  },
  {
    date: '2026-04-15',
    title: 'European Property Bubble Scanner',
    tag: 'FEATURE',
    summary: '38 European cities rated by bubble risk. Each city gets its own page and OG image. r/dataisbeautiful bait. Plus Javea Intelligence Hub, 8 new AEO answer pages, Portugal intelligence rewrite.',
    links: [
      { label: 'Bubble Scanner', href: '/bubble-scanner' },
      { label: 'Javea Hub', href: '/locations/javea' },
    ],
  },
  {
    date: '2026-04-13',
    title: 'MCP Server + Smithery',
    tag: 'API',
    summary: '7 MCP tools exposed to Claude, Cursor, Windsurf. Registered on Smithery. First property platform ever to expose itself via MCP. A2A protocol agent card published.',
    links: [
      { label: 'MCP Server', href: '/mcp-server' },
    ],
  },
  {
    date: '2026-04-11',
    title: 'Avena Terminal Launch',
    tag: 'SHIPPED',
    summary: '1,881 new build properties scored across Costa Blanca, Costa Calida, Costa del Sol. 5-factor Avena Score. APCI index. Zenodo DOI 10.5281/zenodo.19520064. 12 autonomous agents. Oracle AI with 10 analytical tools.',
    links: [
      { label: 'About', href: '/about' },
      { label: 'Methodology', href: '/methodology' },
    ],
  },
];

const TAG_COLORS: Record<ChangelogEntry['tag'], string> = {
  SHIPPED: 'text-primary',
  SYSTEM: 'text-primary',
  FEATURE: 'text-foreground',
  AGENT: 'text-accent',
  API: 'text-foreground/80',
  DESIGN: 'text-foreground/80',
};

export default function ChangelogPage() {
  return (
    <div className="avena-v2 min-h-screen">
      <Nav />

      <main className="pt-16">
        <section className="relative overflow-hidden py-20 sm:py-28">
          <div
            className="pointer-events-none absolute inset-0 opacity-60"
            style={{ background: 'radial-gradient(ellipse at top, hsl(42 85% 64% / 0.22), transparent 60%)' }}
          />
          <div className="relative mx-auto max-w-[1600px] px-5 sm:px-12">
            <div className="max-w-4xl">
              <span className="mb-6 inline-flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.4em] text-primary">
                <span className="h-px w-10" style={{ background: 'hsl(var(--av-primary))' }} />
                Changelog · What\u2019s new
              </span>
              <h1 className="font-serif text-5xl sm:text-7xl lg:text-8xl font-light leading-[0.95] tracking-tight text-foreground">
                Every ship.
                <br />
                <span className="italic text-gold">Nothing hidden</span>.
              </h1>
              <p className="mt-8 max-w-2xl font-light text-base text-muted-foreground sm:text-lg">
                The chronological build log of Avena Terminal. Every feature, every system, every agent.
              </p>
            </div>
          </div>
        </section>

        <section className="relative border-t py-16" style={{ borderColor: 'hsl(var(--av-border) / 0.6)' }}>
          <div className="mx-auto max-w-[1000px] px-5 sm:px-12">
            <ol className="relative">
              {/* Vertical timeline line */}
              <div className="absolute left-[9px] top-2 bottom-2 w-px" style={{ background: 'hsl(var(--av-border))' }} />

              {CHANGELOG.map((entry, i) => (
                <li key={i} className="relative pl-10 pb-12 last:pb-0">
                  {/* Dot */}
                  <span
                    className="absolute left-0 top-2 block h-[18px] w-[18px] rounded-full border-2"
                    style={{
                      background: 'hsl(var(--av-background))',
                      borderColor: entry.tag === 'SHIPPED' || entry.tag === 'SYSTEM' ? 'hsl(var(--av-primary))' : 'hsl(var(--av-border-strong))',
                    }}
                  />

                  <div className="flex items-center gap-3 mb-2">
                    <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground tabular">{entry.date}</span>
                    <span className={`font-mono text-[10px] uppercase tracking-[0.3em] ${TAG_COLORS[entry.tag]}`}>{entry.tag}</span>
                  </div>

                  <h2 className="font-serif text-2xl sm:text-3xl font-light tracking-tight text-foreground mb-3">
                    {entry.title}
                  </h2>

                  <p className="text-base text-muted-foreground font-light leading-relaxed mb-4">{entry.summary}</p>

                  {entry.links && entry.links.length > 0 && (
                    <div className="flex flex-wrap gap-x-5 gap-y-2">
                      {entry.links.map(l => (
                        <Link
                          key={l.href}
                          href={l.href}
                          className="font-mono text-[10px] uppercase tracking-[0.22em] text-primary hover:opacity-80"
                        >
                          {l.label} →
                        </Link>
                      ))}
                    </div>
                  )}
                </li>
              ))}
            </ol>
          </div>
        </section>

        <section className="relative border-t py-12" style={{ borderColor: 'hsl(var(--av-border) / 0.6)' }}>
          <div className="mx-auto max-w-[1000px] px-5 sm:px-12 text-center">
            <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
              Subscribe to the changelog via RSS · <Link href="/feed/intelligence.rss" className="text-primary hover:opacity-80">/feed/intelligence.rss</Link>
            </p>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
