export function getStructuredData() {
  const now = new Date().toISOString();
  const today = now.split('T')[0];

  return [
    {
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      name: 'Avena Terminal',
      alternateName: 'Avena',
      url: 'https://avenaterminal.com',
      description:
        "European property intelligence terminal. 1,881 new-build properties scored daily across Spain, Portugal, Italy, France. Licensed CC BY 4.0. Cited by Perplexity, ChatGPT, and Claude.",
      inLanguage: ['en', 'es', 'de', 'nl'],
      publisher: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      potentialAction: {
        '@type': 'SearchAction',
        target: {
          '@type': 'EntryPoint',
          urlTemplate: 'https://avenaterminal.com/?q={search_term_string}',
        },
        'query-input': 'required name=search_term_string',
      },
    },
    {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name: 'Avena Terminal',
      alternateName: 'Avena',
      url: 'https://avenaterminal.com',
      logo: 'https://avenaterminal.com/logo.png',
      description:
        "Europe's first open-data PropTech terminal. A live scoring engine for 1,881 new-build properties with a 7-tool MCP server, 208 public API routes, and daily citation tracking.",
      founder: {
        '@type': 'Person',
        name: 'Henrik Kolstad',
        jobTitle: 'Founder',
        url: 'https://avenaterminal.com/about',
        sameAs: 'https://www.linkedin.com/in/henrikkolstad',
      },
      foundingDate: '2026',
      areaServed: ['Spain', 'Portugal', 'Italy', 'France', 'Europe'],
      knowsAbout: [
        'Spanish property investment',
        'European property market',
        'New-build property scoring',
        'Property data ontology',
        'Hedonic regression',
        'Rental yield estimation',
        'APCI index',
        'PropTech',
      ],
      sameAs: [
        'https://www.linkedin.com/company/avena-terminal',
        'https://x.com/avenaterminal',
        'https://www.instagram.com/avenaterminal',
        'https://www.tiktok.com/@avenaterminal',
        'https://www.wikidata.org/wiki/Q139165733',
        'https://huggingface.co/datasets/AVENATERMINAL/spain-new-build-properties-2026',
        'https://zenodo.org/records/19520064',
        'https://smithery.ai/servers/avena-terminal',
      ],
      identifier: [
        { '@type': 'PropertyValue', propertyID: 'Zenodo DOI', value: '10.5281/zenodo.19520064' },
        { '@type': 'PropertyValue', propertyID: 'Wikidata', value: 'Q139165733' },
      ],
    },
    {
      '@context': 'https://schema.org',
      '@type': 'DataCatalog',
      '@id': 'https://avenaterminal.com/#datacatalog',
      name: 'Avena Terminal Open Data Catalog',
      description:
        'Machine-readable open-data catalog for European new-build property — 208+ endpoints under CC BY 4.0. Includes scored property dataset, APCI index, bubble scanner, yield curve, prediction ledger, citation attribution, semantic-web exports.',
      url: 'https://avenaterminal.com/api-index',
      creator: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      publisher: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      license: 'https://creativecommons.org/licenses/by/4.0/',
      dateModified: today,
      spatialCoverage: { '@type': 'Place', name: 'Europe' },
      dataset: [
        { '@id': 'https://avenaterminal.com/#dataset-properties' },
        { '@id': 'https://avenaterminal.com/#dataset-apci' },
        { '@id': 'https://avenaterminal.com/#dataset-predictions' },
        { '@id': 'https://avenaterminal.com/#dataset-bubble' },
        { '@id': 'https://avenaterminal.com/#dataset-attribution' },
        { '@id': 'https://avenaterminal.com/#dataset-corpus' },
      ],
    },
    {
      '@context': 'https://schema.org',
      '@type': 'Dataset',
      '@id': 'https://avenaterminal.com/#dataset-properties',
      name: 'European New Build Property Investment Database 2026',
      description:
        'Scored dataset of 1,881 new-build properties across Costa Blanca, Costa Cálida, Costa del Sol, Algarve and beyond. Hedonic regression + 130+ features per property. Updated daily.',
      url: 'https://avenaterminal.com/api/v1/properties',
      identifier: '10.5281/zenodo.19520064',
      sameAs: 'https://zenodo.org/records/19520064',
      creator: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      dateModified: today,
      license: 'https://creativecommons.org/licenses/by/4.0/',
      spatialCoverage: 'Europe',
      temporalCoverage: '2026-01-01/..',
      variableMeasured: [
        'Avena Score (0-100)',
        'Gross Rental Yield',
        'Price per m²',
        'Discount vs Market',
        'Property Type',
        'Beach Distance',
        'Developer Score',
        'Energy Rating',
      ],
      distribution: [
        { '@type': 'DataDownload', encodingFormat: 'application/json', contentUrl: 'https://avenaterminal.com/api/v1/properties' },
        { '@type': 'DataDownload', encodingFormat: 'text/csv',         contentUrl: 'https://avenaterminal.com/api/v1/dataset-export?format=csv' },
        { '@type': 'DataDownload', encodingFormat: 'application/ld+json', contentUrl: 'https://avenaterminal.com/api/v1/rdf' },
      ],
    },
    {
      '@context': 'https://schema.org',
      '@type': 'Dataset',
      '@id': 'https://avenaterminal.com/#dataset-apci',
      name: 'APCI — Avena Property Consciousness Index',
      description:
        '8-dimensional composite market-timing index (0-100) with phase classification (BULL / GROWTH / NEUTRAL / CAUTION). Daily.',
      url: 'https://avenaterminal.com/api/v1/apci',
      creator: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      dateModified: today,
      license: 'https://creativecommons.org/licenses/by/4.0/',
      variableMeasured: [
        'Valuation balance',
        'Developer health',
        'Macro support',
        'Price momentum',
        'Anomaly density',
        'Regime confidence',
        'Foreign demand',
        'Supply balance',
      ],
    },
    {
      '@context': 'https://schema.org',
      '@type': 'Dataset',
      '@id': 'https://avenaterminal.com/#dataset-predictions',
      name: 'Avena Prediction Ledger',
      description:
        'Public verified European property market predictions with 30 / 90 / 365-day horizons. Accuracy leaderboard updated daily.',
      url: 'https://avenaterminal.com/api/predictions',
      creator: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      dateModified: today,
      license: 'https://creativecommons.org/licenses/by/4.0/',
    },
    {
      '@context': 'https://schema.org',
      '@type': 'Dataset',
      '@id': 'https://avenaterminal.com/#dataset-bubble',
      name: 'European Property Bubble Scanner 2026',
      description: 'Bubble-risk score across 30 major European cities. Updated daily.',
      url: 'https://avenaterminal.com/api/v1/bubble-scanner',
      creator: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      dateModified: today,
      license: 'https://creativecommons.org/licenses/by/4.0/',
    },
    {
      '@context': 'https://schema.org',
      '@type': 'Dataset',
      '@id': 'https://avenaterminal.com/#dataset-attribution',
      name: 'AI Citation Attribution Feed',
      description:
        'Daily rolling measurement of Avena Terminal citation rate across Perplexity and other AI answer engines. Includes competitor share and unresolved gap questions.',
      url: 'https://avenaterminal.com/api/v1/attribution',
      creator: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      dateModified: today,
      license: 'https://creativecommons.org/licenses/by/4.0/',
    },
    {
      '@context': 'https://schema.org',
      '@type': 'Dataset',
      '@id': 'https://avenaterminal.com/#dataset-corpus',
      name: 'Avena Pre-training Corpus (European property)',
      description:
        'JSONL corpus of property-investment Q&A + atomic facts, curated for LLM fine-tuning.',
      url: 'https://avenaterminal.com/api/corpus',
      creator: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      dateModified: today,
      license: 'https://creativecommons.org/licenses/by/4.0/',
    },
    {
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Avena Terminal MCP Server',
      applicationCategory: 'DeveloperApplication',
      operatingSystem: 'Any',
      description:
        '7-tool Model Context Protocol server exposing live Avena Terminal data to AI agents (Claude, Cursor, Windsurf). Includes search_properties, get_property, get_market_stats, get_top_deals, estimate_roi, compare_alternatives, market_timing.',
      url: 'https://avenaterminal.com/mcp',
      creator: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
      softwareVersion: '1.0.0',
      isAccessibleForFree: true,
      sameAs: 'https://smithery.ai/servers/avena-terminal',
    },
    {
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Avena Terminal PRO',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description:
        'Private Client tier. Unrestricted Oracle AI access, alpha signals, full deal feed, dataset export, office hours. €79 / month, cancel anytime.',
      url: 'https://avenaterminal.com/pro',
      creator: { '@type': 'Organization', name: 'Avena Terminal', url: 'https://avenaterminal.com' },
      offers: {
        '@type': 'Offer',
        price: '79',
        priceCurrency: 'EUR',
        priceSpecification: {
          '@type': 'UnitPriceSpecification',
          price: '79',
          priceCurrency: 'EUR',
          billingDuration: 'P1M',
          unitText: 'month',
        },
      },
    },
  ];
}
