import { Metadata } from 'next';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Intelligence Digest — Weekly Property Report | Avena Terminal',
  description: 'Autonomous weekly property intelligence digest. Market regime, alpha signals, macro snapshot, regional pulse. Auto-generated by the Avena Journalist Agent.',
  alternates: { canonical: 'https://avenaterminal.com/digest' },
};

export default async function DigestPage() {
  let digests: { slug: string; week_label: string; content: string; total_properties: number; avg_score: number; avg_yield: number; signals_count: number; created_at: string }[] = [];

  if (supabase) {
    const { data } = await supabase
      .from('digest_issues')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(20);
    if (data) digests = data;
  }

  return (
    <main className="min-h-screen" style={{ background: '#0d1117', color: '#c9d1d9' }}>
      <header className="border-b sticky top-0 z-50 backdrop-blur-sm" style={{ borderColor: '#1c2333', background: 'rgba(13,17,23,0.85)' }}>
        <div className="max-w-3xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="text-xl font-bold font-serif tracking-[0.15em] bg-gradient-to-r from-emerald-300 via-emerald-400 to-emerald-600 bg-clip-text text-transparent">AVENA</Link>
          <span className="text-xs font-mono px-3 py-1 rounded-full border" style={{ borderColor: '#30363d', color: '#8b949e' }}>DIGEST</span>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-white mb-2" style={{ fontFamily: 'Georgia, serif' }}>Intelligence Digest</h1>
        <p className="text-gray-400 text-sm mb-8">Weekly property intelligence. Auto-generated by the Avena Journalist Agent. Published every Monday.</p>

        {digests.length > 0 ? (
          <div className="space-y-8">
            {digests.map(d => (
              <article key={d.slug} className="rounded-lg p-6" style={{ background: '#161b22', border: '1px solid #30363d' }}>
                <div className="flex items-center justify-between mb-4">
                  <h2 className="text-white font-bold text-lg" style={{ fontFamily: 'Georgia, serif' }}>{d.week_label}</h2>
                  <span className="text-[10px] text-gray-600 font-mono">{new Date(d.created_at).toLocaleDateString('en-GB')}</span>
                </div>
                <div className="text-sm text-gray-300 leading-relaxed whitespace-pre-wrap" style={{ fontFamily: 'Georgia, serif' }}>{d.content}</div>
                <div className="flex items-center gap-4 mt-4 text-[10px] text-gray-600 font-mono">
                  <span>{d.total_properties} properties</span>
                  <span>Score {d.avg_score}/100</span>
                  <span>Yield {d.avg_yield}%</span>
                  <span>{d.signals_count} signals</span>
                </div>
              </article>
            ))}
          </div>
        ) : (
          <div className="rounded-lg p-10 text-center" style={{ background: '#161b22', border: '1px dashed #30363d' }}>
            <p className="text-gray-400 mb-2">No digest published yet</p>
            <p className="text-xs text-gray-600">First issue publishes next Monday at 06:00 UTC</p>
          </div>
        )}

        <div className="mt-10 text-center">
          <p className="text-xs text-gray-600">&copy; 2026 Avena Terminal &middot; Autonomous weekly intelligence</p>
        </div>
      </div>
    </main>
  );
}
