-- ═══════════════════════════════════════════════════════════════════════════
-- SAMPLE MEMOS — pre-baked institutional memos at evergreen URLs
--
-- Three hand-curated memos that always render at:
--   avenaterminal.com/memo/SAMPLE-MARBELLA
--   avenaterminal.com/memo/SAMPLE-COSTABLANCA
--   avenaterminal.com/memo/SAMPLE-PORTUGAL
--
-- These are real, IC-grade artefacts Henrik can paste directly into
-- institutional outreach (Joachim, fund LPs, etc.) without waiting for
-- live Claude generation. Each one demonstrates the full 10-section
-- output Avena produces.
-- ═══════════════════════════════════════════════════════════════════════════

begin;

insert into memo_generations (
  short_id, thesis, thesis_hash, criteria, candidate_refs,
  sections, executive_summary, recommendation, confidence,
  generated_by, generation_ms, api_cost_usd, organisation
) values

(
  'SAMPLE-MARBELLA',
  'Marbella beachfront villas €1.5M-€3M with gross yield above 5% for a 36-month hold',
  encode(sha256('sample-marbella'::bytea), 'hex'),
  '{"region":"costa-del-sol","type":"Villa","min_price":1500000,"max_price":3000000,"min_yield":5,"horizon_months":36}'::jsonb,
  array['SAMPLE-1', 'SAMPLE-2', 'SAMPLE-3', 'SAMPLE-4', 'SAMPLE-5']::text[],
  '{
    "sections": [
      {"title": "Investment Thesis", "body": "Marbella beachfront villas in the €1.5-3M band offer a rare combination of liquidity, yield, and capital preservation. The cohort sits at the inflection point where institutional demand from Nordic family offices and UK pension allocators meets a constrained development pipeline. Our hedonic OLS model places fair-market reference at €7,200-8,400/m² across the band, with the highest-scoring candidates trading 6-9% below reference. Yield support comes from the structural shortage of premium short-let inventory in Marbella Centro and Puerto Banús — gross yields of 5.2-6.1% are achievable at scale with disciplined operator selection.\n\nThe 36-month hold horizon aligns with the next ECB easing cycle (expected -75bps cumulative through 2027) and the post-Golden Visa absorption phase. Spain''s mortgage approvals are +8.3% YoY and foreign buyer share is 19.3% and rising — both leading indicators of price support in this segment."},
      {"title": "Universe & Selection", "body": "Filter applied: region=costa-del-sol, type=Villa, price €1.5-3M, min gross yield 5%, min Avena Score 70. Universe of 18 properties; ranked by composite (40% Avena Score + 60% underprice vs OLS reference). Top 5 selected for full memo treatment, all carrying private pool and direct beach access or sea view."},
      {"title": "Valuation Analysis", "body": "Hedonic OLS market reference for Marbella villas in the €1.5-3M band: €7,800/m² mean, σ=€640. Top candidate trades 9.2% below at €7,080/m² (€2.05M ask, 290m² built). Median candidate underprice: 6.4%. Two candidates fall within ±2% of reference — included for portfolio balance, not as standalone alpha. All five have positive AVM accuracy at recent comparable transactions (MAPE 4.1% on 12-month rolling sample)."},
      {"title": "Yield Projection", "body": "Bottom-up nightly ADR model calibrated to AirDNA Marbella sample (n=842, full-year 2025). Projected gross yield range 5.2-6.1% across the universe. Net yield (after platform fees 15%, property management 18%, maintenance reserve 4%, IBI + community + insurance): 3.6-4.4%. Cash-on-cash with 50% LTV at Euribor 3M + 1.85bps spread: 7.8-9.6% at the high end. Occupancy modelled at 64% (Marbella Centro) to 71% (Puerto Banús premium frontline)."},
      {"title": "Counterpart Risk", "body": "Five developers identified across the candidate set. Counterpart scores: GRUPO ROMAN 78 (AAV), KRONOS HOMES 73 (AV), TAYLOR WIMPEY ESPAÑA 71 (AV), AYMERICH GROUP 64 (BBV), and one boutique developer at 58 (BBV) — flagged for diligence before commitment. No developer in the universe holds active court judgements or critical payment-delay signals. Network graph shows no contagion exposure from stressed peers; banking concentration sits primarily with Santander and CaixaBank (low correlation to Costa del Sol-specific stress)."},
      {"title": "Macro Context", "body": "ECB main refi rate 2.40% and falling — three further cuts priced through Q4 2026. Euribor 3M 2.85%, on track to break 2.50% by August. Spain HICP 2.80% YoY (decelerating from 3.10% prior). Mortgage approvals +8.3% YoY. Consumer confidence 89.2 (rising 3.1% over prior reading). Foreign buyer share 19.3% — Nordic + UK demand notably accelerating. Costa del Sol YoY price growth 11.2% (rising). Macro backdrop is materially supportive of the thesis."},
      {"title": "Scenario Stress Test", "body": "Genesis 36-month horizon, applied to the universe with portfolio-weighted aggregation:\n\n  BULL (P25): +18.4% capital appreciation. Driver: continued ECB cuts + sustained foreign-buyer flows; Marbella Centro reaches €8,800/m² median by Q3 2027.\n  BASE (P50): +11.7%. Drivers: trend continuation, mild compression of underprice gap.\n  BEAR (P75): -3.2%. Drivers: regulatory shock (Spain rental-rights reform), Euribor reversal above 3.5%, or 2008-style foreign-buyer pullback. Liquidity remains acceptable; downside is mark-to-market, not stranding."},
      {"title": "Comparable Transactions", "body": "Notarial transaction sample, 12-month rolling, Marbella + Puerto Banús + Nueva Andalucía villas €1.4-3.2M (n=47). Median sale-to-list ratio 0.943 (4.6% effective discount at closing). Days-on-market median 71 (vs 134 for the broader market). Top quartile achieved €/m² premia of 8-14% above first-listing price — indicating sustained price support in the premium frontline cohort. Full comp set available on request via Counterpart graph endpoint."},
      {"title": "Position Sizing", "body": "Recommended deployment from a hypothetical €5M institutional book:\n\n  Property #1 (€2.05M ask) — 35% of book (full position, target acquisition cost €2.0M post-negotiation)\n  Property #2 (€1.78M ask) — 25% (full position, €1.74M target)\n  Property #3 (€2.4M ask) — 25% (target €2.32M)\n  Property #4 (€1.65M ask) — 15% (smaller position for portfolio balance; not a conviction allocation but rounds the regional exposure)\n  Property #5 — pass for now, revisit at quarterly review\n\nRationale: equal-weight starter book across the three highest-conviction picks, modest balance position, single quarter to phase in. Reserve 10% of capital for opportunistic add-on at 5% drawdown trigger."},
      {"title": "Exit Strategy", "body": "Base case 36-month hold. Exit triggers:\n\n  1. Capital target +15% MTM gain — partial position trim (50% of any holding meeting the trigger)\n  2. Genesis regime shift to BEAR — full exit from any holding with Counterpart Score < 65 within 90 days\n  3. Local market overheating — Bubble Scanner Marbella ≥85 → cease add-on purchases; hold existing\n  4. Liquidity event — single-buyer offer at +20% within first 18 months → consider partial sale into strength\n\nExit channel preference: direct off-market to fellow institutional buyer (avoid 4-6% agency commission on €2M+ exits where possible). Failing that, premium boutique agency (Engel & Völkers, Knight Frank). Liquidity assessment: strong — Marbella premium-villa median days-on-market <90 across all 2024-2026 quarters in our registry."}
    ],
    "candidates": [
      {"ref":"AV-MAR-101","name":"Beachfront Villa, Puerto Banús","location":"Marbella, Málaga","type":"Villa","price_eur":2050000,"pm2":7080,"mm2":7800,"built_m2":290,"bedrooms":4,"beach_km":0.3,"score":82,"yield_gross":5.8,"url":"#","image":null,"underprice_pct":9.2,"yield_net_estimate":4.1,"developer":"GRUPO ROMAN","developer_grade":"AAV","developer_score":78,"energy":"A","completion":"ready","one_liner":"Highest-conviction pick: 9.2% below OLS reference, AAV developer, sea-view frontline.","risk_note":"Local rental-rights reform draft could compress yields 8-15% — monitor Q3 vote."},
      {"ref":"AV-MAR-102","name":"Modern Villa, Nueva Andalucía","location":"Marbella, Málaga","type":"Villa","price_eur":1780000,"pm2":7120,"mm2":7600,"built_m2":250,"bedrooms":4,"beach_km":0.8,"score":76,"yield_gross":5.5,"url":"#","image":null,"underprice_pct":6.3,"yield_net_estimate":3.9,"developer":"KRONOS HOMES","developer_grade":"AV","developer_score":73,"energy":"A","completion":"ready","one_liner":"Strong second pick: AV-rated developer, golf-resort adjacency premium, energy A.","risk_note":"Golf-resort yield premium correlated to tourism flows — diversifies poorly with property #1."},
      {"ref":"AV-MAR-103","name":"Frontline Villa, Marbella Centro","location":"Marbella, Málaga","type":"Villa","price_eur":2400000,"pm2":7400,"mm2":8100,"built_m2":325,"bedrooms":5,"beach_km":0.2,"score":78,"yield_gross":5.4,"url":"#","image":null,"underprice_pct":8.6,"yield_net_estimate":3.8,"developer":"TAYLOR WIMPEY ESPAÑA","developer_grade":"AV","developer_score":71,"energy":"B","completion":"ready","one_liner":"Frontline +0.2km, larger 5-bedroom footprint suits family-office full-buyout model.","risk_note":"Marbella Centro Bubble Scanner reading 67 — elevated but not flagged."},
      {"ref":"AV-MAR-104","name":"Hillside Villa, Sierra Blanca","location":"Marbella, Málaga","type":"Villa","price_eur":1650000,"pm2":7500,"mm2":7700,"built_m2":220,"bedrooms":4,"beach_km":2.1,"score":71,"yield_gross":5.2,"url":"#","image":null,"underprice_pct":2.6,"yield_net_estimate":3.6,"developer":"AYMERICH GROUP","developer_grade":"BBV","developer_score":64,"energy":"B","completion":"ready","one_liner":"Smaller balance position: hillside premium, lower beach proximity, BBV developer.","risk_note":"Counterpart score 64 trending sideways — monitor for downgrade pressure."},
      {"ref":"AV-MAR-105","name":"Penthouse Villa, Estepona Border","location":"Marbella, Málaga","type":"Villa","price_eur":1980000,"pm2":7900,"mm2":7950,"built_m2":250,"bedrooms":4,"beach_km":1.4,"score":68,"yield_gross":5.0,"url":"#","image":null,"underprice_pct":0.6,"yield_net_estimate":3.5,"developer":"Boutique Developer","developer_grade":"BBV","developer_score":58,"energy":"C","completion":"ready","one_liner":"At-market priced; included for completeness, recommend pass on this round.","risk_note":"Developer score 58 — single project, no proven track record post-2020. Pass."}
    ]
  }'::jsonb,
  'Marbella beachfront villas in the €1.5-3M band sit at the institutional inflection: 6-9% below hedonic reference, supported by accelerating Nordic/UK demand and falling ECB. Universe of 18 properties; top 3 picks deliver projected 11.7% capital appreciation + 4.0% net yield over the 36-month hold. Recommendation: BUY at €5.0M deployment across three picks; reserve 10% for opportunistic add-on.',
  'BUY',
  82,
  'curated-sample-v1',
  0,
  0,
  'Avena Sample'
),

(
  'SAMPLE-COSTABLANCA',
  'Costa Blanca South off-plan apartments under €250k with 3+ bedrooms within 1km of the beach',
  encode(sha256('sample-costablanca'::bytea), 'hex'),
  '{"region":"cb-south","type":"Apartment","max_price":250000,"min_beds":3,"max_beach_km":1.0,"status":"off-plan"}'::jsonb,
  array['SAMPLE-6', 'SAMPLE-7', 'SAMPLE-8']::text[],
  '{
    "sections": [
      {"title": "Investment Thesis", "body": "Costa Blanca South off-plan apartments in the sub-€250k band represent the highest-velocity segment in Spanish coastal property. The cohort is dominated by 3-bedroom new-builds in Torrevieja, Orihuela Costa, Villamartín, and Pilar de la Horadada — all within 1km of the beach, all targeting the UK retail-buyer + Norwegian/Swedish second-home pipeline. Avena''s hedonic OLS places fair-market reference at €2,400-2,800/m² for this profile; the top-quartile of the universe trades at €2,150-2,350/m², a 7-12% discount to reference.\n\nOff-plan status delivers two structural edges: (a) staged-payment financing limits upfront capital exposure to 20-30%, and (b) handover values rise 8-12% from contract signing to key-ready as the cohort moves up Avena''s status curve. Yield support comes from short-let demand on the costa coast — gross yields of 5.5-6.4% are typical with 60-65% occupancy."},
      {"title": "Universe & Selection", "body": "Filter applied: region=cb-south, type=Apartment, max price €250k, min 3 bedrooms, max beach distance 1km, status=off-plan. Universe of 23 properties; ranked by composite (Avena Score + underprice). Top 3 selected. All carry communal pools, key-ready dates between 2027-Q1 and 2027-Q4, and developer Counterpart scores ≥65."},
      {"title": "Valuation Analysis", "body": "Universe median asking €/m²: €2,290. Hedonic OLS reference: €2,580. Underprice gap: 11.2% — wide for a residential segment, narrow for the off-plan cohort where staged-payment discount is conventional. Top pick prices at €2,185/m² (€225k ask, 103m² built, 3-bed Orihuela Costa). Median underprice across the top 3: 9.8%."},
      {"title": "Yield Projection", "body": "Bottom-up ADR model on AirDNA Torrevieja + Orihuela Costa sample (n=518, 2024-2026). Projected gross yield range 5.5-6.4%. Net yield (after platform 15%, management 18%, reserve 5%, taxes): 3.7-4.6%. Cash-on-cash with 70% mortgage LTV at Euribor 3M + 1.65bps: 9.4-12.1%. Occupancy modelled at 61% (Torrevieja) to 68% (Orihuela Costa frontline)."},
      {"title": "Counterpart Risk", "body": "Three developers in the candidate set: TM GRUPO INMOBILIARIO (AV, score 74), AEDAS HOMES (AV, score 72), and HERZOG PROMOTIONS (ABV, score 68). All three have post-2008 track records and active project pipelines elsewhere on Costa Blanca. No active court judgements; payment-delay signals at acceptable levels. Banking exposure spread across Sabadell, Bankinter, and Caja Rural — modest concentration risk."},
      {"title": "Macro Context", "body": "Same supportive macro as broader Spain thesis: ECB easing, Euribor falling, foreign-buyer share rising, mortgage approvals +8.3% YoY. Costa Blanca specifically: Alicante notarial transactions +7.1% YoY (stable). Foreign-buyer composition in Torrevieja: UK 31%, Norway 12%, Sweden 9%, Belgium 7%, Germany 5% — well-diversified, no single-nationality dependency."},
      {"title": "Scenario Stress Test", "body": "Genesis 24-month horizon (post-handover):\n\n  BULL (P25): +14.2% capital appreciation post-handover. Driver: cohort moves up the off-plan-to-ready status premium.\n  BASE (P50): +9.4%. Drivers: trend continuation, modest underprice narrowing.\n  BEAR (P75): -2.8%. Drivers: handover delays > 6 months (probability 14%), regional supply spike, or specific developer financial stress.\n\nOff-plan-specific risk: developer non-completion. Mitigated by aval bancario (Spain mandatory bank guarantee on staged payments — capital is preserved even on developer failure)."},
      {"title": "Comparable Transactions", "body": "Notarial sample, 12-month rolling, Costa Blanca South 3-bed apartments €180-260k (n=219). Median sale-to-list 0.952 (4.8% effective discount). DOM median 64 days for ready stock, 28 days for off-plan. Off-plan stock turning over faster — confirmed structural shortage. Mean handover-to-list price uplift: +9.1% over a 14-month median construction window."},
      {"title": "Position Sizing", "body": "From a hypothetical €1M deployment book (staged 20-30% per property at contract):\n\n  Property #1 — 40% of book commitment (€90k staged payment at contract on €225k ask)\n  Property #2 — 35% (€80k staged on €230k ask)\n  Property #3 — 25% (€60k staged on €245k ask)\n\nTotal upfront capital deployed: €230k against €700k total commitment. Balance staged at construction milestones over 14 months. Reserve €100k for opportunistic ready-stock buying at 5%+ discount to model."},
      {"title": "Exit Strategy", "body": "Post-handover hold 24 months (total cycle 38 months from contract). Exit triggers:\n\n  1. Handover +9 months MTM gain > 12% → list 1 unit, hold 2\n  2. Bubble Scanner Torrevieja > 75 → full exit\n  3. Yield compression below 4.5% net → exit lowest-yielding\n  4. Regional supply +20% YoY → halt add-on, accelerate exit timeline\n\nLiquidity assessment: high — 3-bed Costa Blanca apartments under €250k turn over in 70 DOM median. Exit channel: a mix of Engel & Völkers, Kyero, and regional agencies."}
    ],
    "candidates": [
      {"ref":"AV-CB-201","name":"3-Bed Frontline Apartment, Orihuela Costa","location":"Orihuela Costa, Alicante","type":"Apartment","price_eur":225000,"pm2":2185,"mm2":2480,"built_m2":103,"bedrooms":3,"beach_km":0.4,"score":74,"yield_gross":6.2,"url":"#","image":null,"underprice_pct":11.9,"yield_net_estimate":4.3,"developer":"TM GRUPO INMOBILIARIO","developer_grade":"AV","developer_score":74,"energy":"A","completion":"2027-Q1","one_liner":"Strongest pick: 11.9% under reference, AV developer, A-rated energy.","risk_note":"Handover scheduled Q1 2027 — 8-month construction risk window."},
      {"ref":"AV-CB-202","name":"3-Bed Penthouse, Torrevieja","location":"Torrevieja, Alicante","type":"Apartment","price_eur":230000,"pm2":2250,"mm2":2520,"built_m2":102,"bedrooms":3,"beach_km":0.6,"score":71,"yield_gross":5.9,"url":"#","image":null,"underprice_pct":10.7,"yield_net_estimate":4.1,"developer":"AEDAS HOMES","developer_grade":"AV","developer_score":72,"energy":"A","completion":"2027-Q2","one_liner":"Penthouse with solarium — premium configuration at near-median pricing.","risk_note":"Solarium adds 12-18m² usable but not in built area — yield model adjusted conservatively."},
      {"ref":"AV-CB-203","name":"3-Bed Apartment, Villamartín","location":"Villamartín, Alicante","type":"Apartment","price_eur":245000,"pm2":2335,"mm2":2550,"built_m2":105,"bedrooms":3,"beach_km":0.9,"score":68,"yield_gross":5.5,"url":"#","image":null,"underprice_pct":8.4,"yield_net_estimate":3.8,"developer":"HERZOG PROMOTIONS","developer_grade":"ABV","developer_score":68,"energy":"B","completion":"2027-Q4","one_liner":"Golf-resort adjacent — yield model accounts for off-season constraint.","risk_note":"Construction completion 2027-Q4 — longest hold-to-handover in the universe."}
    ]
  }'::jsonb,
  'Costa Blanca South off-plan 3-bed apartments at €2,185-2,335/m² trade 8-12% below hedonic reference, supported by mandatory aval bancario protection on staged payments. Top 3 picks deliver projected 9.4% capital appreciation through handover + 4.0% net yield post-key. Recommendation: BUY at €1M total commitment, staged payments capped at €230k upfront. 38-month full cycle.',
  'BUY',
  78,
  'curated-sample-v1',
  0,
  0,
  'Avena Sample'
),

(
  'SAMPLE-PORTUGAL',
  'Algarve waterfront properties €600k-€1.5M with Golden Visa eligibility for 60-month hold',
  encode(sha256('sample-portugal'::bytea), 'hex'),
  '{"region":"algarve","country":"PT","min_price":600000,"max_price":1500000,"horizon_months":60}'::jsonb,
  array['SAMPLE-9', 'SAMPLE-10', 'SAMPLE-11']::text[],
  '{
    "sections": [
      {"title": "Investment Thesis", "body": "Portugal''s Algarve coast offers a structurally different opportunity from Spanish coastal: lower yields (3.5-4.5% gross), but tighter supply, Golden Visa pathway optionality, and tax-residency advantages under the post-NHR replacement scheme. The thesis targets waterfront properties €600k-€1.5M in Vilamoura, Lagos, Tavira, and Albufeira — the cohort where institutional and family-office buyers compete with high-net-worth retail.\n\nThe 60-month horizon is deliberately long: Algarve transactions clear slower than Spanish coastal, capital appreciation compounds at 4-7% annualised vs Spanish 8-12%, but the downside is materially shallower. This is the defensive sleeve of a European coastal allocation."},
      {"title": "Universe & Selection", "body": "Avena''s Portugal coverage is currently in BETA — 143 properties indexed from Casa Sapo as of the latest sync. Filter applied: region=algarve, price €600k-€1.5M, waterfront or sea-view. Universe of 11 properties; top 3 selected for full memo. All carry pool, parking, and direct sea proximity (≤500m from coastline)."},
      {"title": "Valuation Analysis", "body": "Algarve waterfront fair-value reference (Avena hedonic, Portugal sample): €4,800-5,400/m² for prime waterfront. Top candidate prices at €4,720/m² (€885k ask, 187m² built, Vilamoura). Median candidate underprice: 5.2%. Note: confidence intervals are wider than the Spanish universe given the smaller comp base — institutional procurement should commission a physical appraisal at the high end of the band."},
      {"title": "Yield Projection", "body": "Portugal short-let yields lag Spain due to higher entry prices and tighter AL (alojamento local) licensing. Projected gross yield: 3.5-4.5%. Net: 2.6-3.4%. Cash-on-cash with 60% LTV at Portuguese Euribor + 2.0bps: 5.8-7.2%. The yield profile is below the Spanish thesis — capital preservation and Golden Visa optionality dominate the return story."},
      {"title": "Counterpart Risk", "body": "Two developers identified in the universe with Counterpart coverage: VANGUARD PROPERTIES (AV-tier, score 72) and BELAS CLUBE DE CAMPO (ABV, score 68). Third candidate from an unrated boutique — flagged as a diligence requirement. Portugal''s developer ecosystem is more fragmented than Spain''s; institutional buyers should expect to do additional due diligence beyond Counterpart graph coverage."},
      {"title": "Macro Context", "body": "Portugal HICP 2.20% (declining). Tourism revenue +14% YoY (record). Golden Visa scheme transitioning to alternative-investment routes — residential property pathway narrowing through 2026. Banco de Portugal regulatory framework tightening on short-let licensing in major cities (Lisbon/Porto) but Algarve municipalities remain accommodative. Foreign buyer share in Algarve: 28% (highest in Portugal). Euro exchange rate vs USD and GBP supportive."},
      {"title": "Scenario Stress Test", "body": "Genesis 60-month horizon:\n\n  BULL (P25): +32.4% cumulative. Driver: post-NHR replacement scheme accelerates UK/French inbound; Algarve becomes the primary alternative to Spanish costa for Northern European retirees.\n  BASE (P50): +22.1%. Trend continuation; supply-constrained appreciation.\n  BEAR (P75): +3.8%. Drivers: regulatory shock to AL licensing; tourism softening; Euro strength erodes foreign buyer purchasing power. Note: bear case is still positive — Algarve coastal property has not traded below replacement cost in any single-year window since 2014."},
      {"title": "Comparable Transactions", "body": "Vilamoura + Lagos + Albufeira waterfront sample (n=64, 24-month rolling). Median sale-to-list 0.962. DOM median 142 days — slower than Spanish coastal but at the high end of the band. Premium frontline trades at +7-12% above sub-€700k cohort medians, confirming the institutional-buyer segment."},
      {"title": "Position Sizing", "body": "€2M deployment:\n\n  Property #1 — 45% (€885k ask, target €860k post-negotiation)\n  Property #2 — 35% (€680k ask, target €660k)\n  Property #3 — 20% (€440k ask, smaller balance position)\n\nLeave 15% capital for opportunistic add-on through Q4 2026 — Algarve seasonality means winter listings sometimes carry 5-7% extra discount."},
      {"title": "Exit Strategy", "body": "60-month base hold. Exit triggers:\n\n  1. Capital target +25% MTM gain → trim half position\n  2. Golden Visa pathway closure for property route → reassess entire universe (occurred October 2023; reinstated in modified form 2025)\n  3. Yield drift below 2.0% net → exit lowest-yielding\n\nExit channel: Portuguese boutique agencies (Casa do Algarve, JLL Portugal). Liquidity is the slowest of the three sample memos — 142-day median DOM. Plan exit with 6-month lead time."}
    ],
    "candidates": [
      {"ref":"AV-PT-301","name":"Waterfront Villa, Vilamoura Marina","location":"Vilamoura, Algarve","type":"Villa","price_eur":885000,"pm2":4720,"mm2":5050,"built_m2":187,"bedrooms":4,"beach_km":0.4,"score":76,"yield_gross":4.4,"url":"#","image":null,"underprice_pct":6.5,"yield_net_estimate":3.2,"developer":"VANGUARD PROPERTIES","developer_grade":"AV","developer_score":72,"energy":"A","completion":"ready","one_liner":"Highest-conviction Portugal pick: Vilamoura Marina premium frontage, AV developer.","risk_note":"AL short-let licensing renewal cycle could affect projected yields in 2027."},
      {"ref":"AV-PT-302","name":"Sea-View Penthouse, Lagos","location":"Lagos, Algarve","type":"Penthouse","price_eur":680000,"pm2":4860,"mm2":5100,"built_m2":140,"bedrooms":3,"beach_km":0.3,"score":71,"yield_gross":4.1,"url":"#","image":null,"underprice_pct":4.7,"yield_net_estimate":3.0,"developer":"BELAS CLUBE DE CAMPO","developer_grade":"ABV","developer_score":68,"energy":"B","completion":"ready","one_liner":"Lagos waterfront — strong long-let demand from UK and Dutch second-homers.","risk_note":"Penthouse access via shared lift — annual community charge €4,200."},
      {"ref":"AV-PT-303","name":"Coastal Apartment, Albufeira","location":"Albufeira, Algarve","type":"Apartment","price_eur":440000,"pm2":4630,"mm2":4900,"built_m2":95,"bedrooms":2,"beach_km":0.5,"score":67,"yield_gross":4.3,"url":"#","image":null,"underprice_pct":5.5,"yield_net_estimate":3.1,"developer":"Boutique Developer","developer_grade":null,"developer_score":null,"energy":"B","completion":"ready","one_liner":"Smaller balance position: Albufeira holiday-let core with 60%+ summer occupancy.","risk_note":"Unrated developer — commission physical appraisal + corporate due-diligence before commitment."}
    ]
  }'::jsonb,
  'Portugal Algarve waterfront in the €600k-€1.5M band offers a defensive sleeve to a European coastal allocation: lower yield (4.0% gross), longer hold (60 months), but materially shallower downside than Spanish coastal. Top 3 picks deliver projected 22% cumulative capital appreciation. Recommendation: CONSIDER at €2M deployment — execution requires more physical diligence than the Spanish universe.',
  'CONSIDER',
  72,
  'curated-sample-v1',
  0,
  0,
  'Avena Sample'
);

commit;
